### ISSUE TITLE
Consider writing analyzed.toml file

### ISSUE THREAD

**Issue by natalieparellano** [cloudfoundry/cnbapplifecycle#21]
I noticed that you are skipping the analyze phase, which for now is probably okay as we fallback to reading /etc/os-release during detect, which will give us distro information for target matching. So, the lifecycle is not going to hard-fail buildpacks during detect for target mismatch.

However, some buildpacks may start to inspect the `CNB_TARGET_*` env vars that they get during detect (I believe Heroku’s buildpacks are starting to do this although Paketo is not yet there), and opt out of the build if the value is missing or unexpected. It would be safer to pre-write an analyzed.toml file with the expected target data for the run “image” to avoid surprises.

**Comment by pbusko** [comment]
Thank you @natalieparellano for reporting this. We skipped the analyze phase completely because there's actually no images to analyse (neither previous nor run image), as the produced result is a Droplet.

However we completely missed the `CNB_TARGET_*` part, will be fixed in https://github.com/cloudfoundry/cnbapplifecycle/pull/22
